### ISSUE TITLE
semver module not found

### ISSUE THREAD

**Issue by mike-jianxin-mo** [DomonJi/monkov#2]
when executing the "npm run dev-client", I got the following error.

module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

PS. which commit is stable commit?

**Comment by DomonJi** [comment]
It seems like npm's bug, maybe you can find solutions in [stackoverflow](http://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver) and [npm#15558](https://github.com/npm/npm/issues/15558).
This project is only for practice and I didn't do any test.
It works fine in my environment.
